export {default as ForgotPasswordPage} from './ForgotPasswordPage';
export {default as LoginPage} from './LoginPage';
export {default as MobileLoginPage} from './MobileLoginPage';
export {default as RegisterPage} from './RegisterPage';
export {default as ResetPasswordPage} from './ResetPasswordPage';
export {default as UserSettingsPage} from "./UserSettingsPage";
export {default as AdminHomePage} from "./AdminHomePage";
export {default as PatientSearchPage} from "./PatientSearchPage";
export {default as MobilePromptsPage} from "./MobilePromptsPage"
export {default as LoadingPage} from "./LoadingPage"