export {default as ForgotPasswordPage} from './ForgotPasswordPage';
export {default as Home} from './Home';
export {default as LoginPage} from './LoginPage';
export {default as RegisterPage} from './RegisterPage';
export {default as UploadFilePage} from './UploadFilePage';
export {default as BasicForm} from "./BasicForm";
export {default as ResetPasswordPage} from './ResetPasswordPage';
export {default as UserSettingsPage} from "./UserSettingsPage";
export {default as AdminHomePage} from "./AdminHomePage";