export { AbdomenPage } from "./AbdomenPage/AbdomenPage";
export { default as AppointmentsPage } from "./AppointmentsPage/AppointmentsPage";
export { DemographicPage } from "./DemographicPage/DemographicPage";
export { GeneralPage } from "./GeneralPage/GeneralPage";
export { HeartPage } from "./HeartPage/HeartPage";
export { LegsPage } from "./LegsPage/LegsPage";
export { LungsPage } from "./LungsPage/LungsPage";
export { MessagesPage } from "./MessagesPage/Messages";
export { PulsesPage } from "./PulsesPage/PulsesPage";
export { default as SummaryPage } from "./SummaryPage/SummaryPage";